name: Run Data Pipeline

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t valorant-project .

      - name: Validate scraper container
        run: |
          docker run --rm \
          valorant-project \
          python -c "import pipeline.scrape_pipeline; print('Scraper container OK')"
      
      - name: Create test raw data
        run: |
          mkdir -p data/raw
          echo "artifact test" > data/raw/test.txt
      
      - name: Upload raw data artifact 
        uses: actions/upload-artifact@v4
        with:
          name: raw-data
          path: data/raw/

      # - name: Run scraper
      #   run: |
      #     docker run --rm \
      #     -v "${{ github.workspace }}/data/raw:/valorant/data/raw" \
      #     valorant-project \
      #     python -m pipeline.scraper_pipeline

      - name: Upload raw data artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-data
          path: data/raw/

  gcp:
    needs: scrape
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download raw data artifact
        uses: actions/download-artifact@v4
        with:
          name: raw-data
          path: data/raw/

  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v3
  #       with:
  #         workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
  #         service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  #     - name: Build Docker Image
  #       run: docker build -t valorant-project .

  #     - name: Run GCP pipeline
  #       run: |
  #         docker run --rm \
  #         -v "${{ github.workspace }}/data/raw:/valorant/data/raw" \
  #         valorant-project \
  #         python -m pipeline.gcp_pipeline
