name: Run dbt CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-bigquery==1.12.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Create dbt Profile
        run: |
          mkdir ~/.dbt
          
          cat > ~/.dbt/profiles.yml << 'EOF'
          valorant:
            target: ci
            outputs:
              ci:
                dataset: dbt_ci
                location: asia-southeast2
                method: oauth
                priority: interactive
                project: valorant-project-2026
                threads: 4
                type: bigquery

              prod:
                dataset: dbt_prod
                location: asia-southeast2
                method: oauth
                priority: interactive
                project: valorant-project-2026
                threads: 4
                type: bigquery
          EOF

      - name: Install dbt Packages
        working-directory: ./valorant
        run: dbt deps

      - name: Check dbt Connection - CI
        if: github.event_name == 'pull_request'
        working-directory: ./valorant
        run: dbt debug --target ci

      - name: Run dbt build - CI
        if: github.event_name == 'pull_request'
        working-directory: ./valorant
        run: dbt build --target ci
      
      - name: Check dbt Connection - Production
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        working-directory: ./valorant
        run: dbt debug --target prod

      - name: Run dbt build - Production
        if: github.event_name == 'push' && github.ref == 'refs/head/main'
        working-directory: ./valorant
        run: dbt build -- target prod