version: 3

sources:
  - name: bronze
    database: valorant-project-2026
    schema: "{{ target.name }}_bronze"

    tables:
      - name: tours
      - name: matches
      - name: games_overview
      - name: games_economy
      - name: players
      - name: map_vetos